### ISSUE TITLE
Variable DEV_MODE needs to be set to False

### ISSUE THREAD

**Issue by pdefusco** [cloudera/CML_AMP_Continuous_Model_Monitoring#1]
Hey Andrew, 
Nice job on this AMP! I was trying to launch this from a CML project and noticed it wouldn't run until I edited the default value of the DEV_MODE var to False (from false with lower case f). 
If it's something you can edit please go ahead when you can. Thanks!
Paul

**Comment by andrewrreed** [comment]
Hey Paul - thanks for the note. This is actually a known issue per DSE-19177 and will be triaged accordingly. Thanks!
